# =====================================
# Flutter Android build optimization
# =====================================

org.gradle.jvmargs=-Xmx4608m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enable parallel build and daemon for faster compilation
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Kotlin daemon settings (stabil untuk Windows)
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# AndroidX settings
android.useAndroidX=true
android.enableJetifier=true

# Enable caching to reduce rebuild times
org.gradle.caching=true

# Suppress warnings caused by drive differences (C: vs G:)
org.gradle.warning.mode=none

# =====================================
# Flutter specific
# =====================================
FLUTTER_BUILD_DIR=build
